Smarteon/loxone-java

- gradle.properties
- src/main/java/cz/smarteon/loxone/config/Control.java
- src/test/groovy/cz/smarteon/loxone/config/ControlTest.groovy
> Introduce deserialization of isSecured property

- src/main/java/cz/smarteon/loxone/LoxoneWebsocketClient.java
- src/main/java/cz/smarteon/loxone/message/MessageHeader.java
- src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketAT.groovy
- src/test/groovy/cz/smarteon/loxone/message/MessageHeaderTest.groovy
> Introduce keepalive

- build.gradle.kts
> Use jackson with fixed security bugs (2.9.5)

- README.md
- examples/example/build.gradle.kts
- examples/example/gradle/wrapper/gradle-wrapper.properties
- examples/example/gradlew
- examples/example/gradlew.bat
- examples/example/settings.gradle.kts
- examples/example/src/main/java/cz/smarteon/loxone/example/LoxoneJavaExample.java
- examples/example/src/main/resources/simplelogger.properties
> Introduce first usage example

- build.gradle.kts
- src/main/java/cz/smarteon/loxone/Codec.java
- src/main/java/cz/smarteon/loxone/Command.java
- src/main/java/cz/smarteon/loxone/LoxoneAuth.java
- src/main/java/cz/smarteon/loxone/LoxoneHttp.java
- src/main/java/cz/smarteon/loxone/Protocol.java
- src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
> Support redirect and introduce Command class

- src/main/java/cz/smarteon/loxone/Command.java
- src/main/java/cz/smarteon/loxone/system/status/AirBaseExtension.java
- src/main/java/cz/smarteon/loxone/system/status/AirDevice.java
- src/main/java/cz/smarteon/loxone/system/status/BasicExtension.java
- src/main/java/cz/smarteon/loxone/system/status/DaliDevice.java
- src/main/java/cz/smarteon/loxone/system/status/DaliExtension.java
- src/main/java/cz/smarteon/loxone/system/status/Device.java
- src/main/java/cz/smarteon/loxone/system/status/Extension.java
- src/main/java/cz/smarteon/loxone/system/status/MiniserverStatus.java
- src/main/java/cz/smarteon/loxone/system/status/OneWireDevice.java
- src/main/java/cz/smarteon/loxone/system/status/OneWireExtension.java
- src/main/java/cz/smarteon/loxone/system/status/RS485Extension.java
- src/main/java/cz/smarteon/loxone/system/status/RelayExtension.java
- src/main/java/cz/smarteon/loxone/system/status/TreeBranch.java
- src/main/java/cz/smarteon/loxone/system/status/TreeDevice.java
- src/main/java/cz/smarteon/loxone/system/status/TreeExtension.java
- src/test/groovy/cz/smarteon/loxone/message/SerializationSupport.groovy
- src/test/groovy/cz/smarteon/loxone/system/status/MiniserverStatusTest.groovy
- src/test/resources/system/status/status.xml
- src/test/resources/system/statusPlain.xml
> Introduce support for system status API

- src/main/java/cz/smarteon/loxone/system/status/DmxExtension.java
- src/main/java/cz/smarteon/loxone/system/status/Extension.java
- src/test/groovy/cz/smarteon/loxone/system/status/MiniserverStatusTest.groovy
- src/test/resources/system/status/status.xml
> Introduce DMX extension

- src/main/java/cz/smarteon/loxone/system/status/AirBaseExtension.java
- src/main/java/cz/smarteon/loxone/system/status/AirDevice.java
- src/main/java/cz/smarteon/loxone/system/status/DaliDevice.java
- src/main/java/cz/smarteon/loxone/system/status/DaliExtension.java
- src/main/java/cz/smarteon/loxone/system/status/DevicesProvider.java
- src/main/java/cz/smarteon/loxone/system/status/Extension.java
- src/main/java/cz/smarteon/loxone/system/status/MiniserverStatus.java
- src/main/java/cz/smarteon/loxone/system/status/OneWireExtension.java
- src/main/java/cz/smarteon/loxone/system/status/TreeBranch.java
- src/main/java/cz/smarteon/loxone/system/status/TreeDevice.java
- src/main/java/cz/smarteon/loxone/system/status/TreeExtension.java
* Add some javadoc
* Use plain booleans to avoid nulls
* Fallback to empty collections
> Make the status more robust.

- src/main/java/cz/smarteon/loxone/AuthListener.java
- src/main/java/cz/smarteon/loxone/LoxoneAuth.java
- src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
- src/main/java/cz/smarteon/loxone/Protocol.java
- src/main/java/cz/smarteon/loxone/TokenState.java
- src/main/java/cz/smarteon/loxone/message/EncryptedCommand.java
- src/main/java/cz/smarteon/loxone/message/LoxoneMessageCommand.java
- src/main/java/cz/smarteon/loxone/message/LoxoneValueTypeResolver.java
- src/main/java/cz/smarteon/loxone/message/Token.java
- src/test/groovy/cz/smarteon/loxone/MockWebSocketServer.groovy
- src/test/groovy/cz/smarteon/loxone/TokenStateTest.groovy
- src/test/groovy/cz/smarteon/loxone/message/EncryptedCommandTest.groovy
- src/test/groovy/cz/smarteon/loxone/message/TokenTest.groovy
- src/test/resources/message/token.json
> Process and memoize auth token

- src/main/java/cz/smarteon/loxone/LoxoneEndpoint.java
- src/main/java/cz/smarteon/loxone/LoxoneHttp.java
- src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
- src/test/groovy/cz/smarteon/loxone/LoxoneEndpointTest.groovy
- src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketAT.groovy
- src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
> Introduce LoxoneEndpoint wrapping the uri logic

- src/main/java/cz/smarteon/loxone/LoxoneAuth.java
This is a workaround for issue #72
> Use getToken instead of authwithtoken

- src/main/java/cz/smarteon/loxone/app/MiniserverType.java
- src/test/groovy/cz/smarteon/loxone/app/MiniserverTypeTest.groovy
Also add fallback to UNKNOWN type.
Resolves #78
> Support 2nd gen. miniserver

- build.gradle.kts
- src/main/java/cz/smarteon/loxone/Codec.java
- src/main/java/cz/smarteon/loxone/LoxoneAuth.java
- src/main/java/cz/smarteon/loxone/LoxoneCrypto.java
- src/main/java/cz/smarteon/loxone/message/PubKeyInfo.java
- src/test/groovy/cz/smarteon/loxone/CodecTest.groovy
- src/test/resources/simplelogger.properties
> Upgrade websocket library to 1.4.0

- src/test/groovy/cz/smarteon/loxone/LoxoneAuthTest.groovy
> Make the LoxoneAuthTest deterministic

- src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
- src/main/java/cz/smarteon/loxone/LoxoneWebSocketListener.java
- src/main/java/cz/smarteon/loxone/LoxoneWebsocketClient.java
- src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
Added new method to LoxoneWebSocketListener to notify the closure of a socket.
> Adding websocketclosed listener

- src/main/java/cz/smarteon/loxone/LoxoneHttp.java
Modification of the LoxoneHttp class to change "get" method to support 307 error
> change to support 307 error

- src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
- src/main/java/cz/smarteon/loxone/LoxoneWebSocketListener.java
- src/main/java/cz/smarteon/loxone/LoxoneWebsocketClient.java
- src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
- src/test/groovy/cz/smarteon/loxone/LoxoneWebsocketClientTest.groovy
> Introduce local end socket closed event

- build.gradle.kts
- src/main/java/cz/smarteon/loxone/LoxoneHttp.java
- src/test/groovy/cz/smarteon/loxone/LoxoneHttpTest.groovy
> Introduce last called HTTP URL

- src/main/java/cz/smarteon/loxone/Loxone.java
- src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
- src/main/java/cz/smarteon/loxone/LoxoneWebSocketListener.java
- src/test/groovy/cz/smarteon/loxone/LoxoneTest.groovy
- src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
This change is not backward compatible
> Allow to register more WebSocketListeners

- build.gradle.kts
- src/main/java/cz/smarteon/loxone/system/status/TreeDevice.java
- src/main/java/cz/smarteon/loxone/system/status/TreeToAirBridge.java
- src/test/groovy/cz/smarteon/loxone/system/status/MiniserverStatusTest.groovy
- src/test/resources/system/status/status.xml
> Introduce Tree2AirBridge in status

- src/main/java/cz/smarteon/loxone/message/LoxoneMessage.java
- src/test/groovy/cz/smarteon/loxone/message/LoxoneMessageTest.groovy
- src/test/resources/message/getToken401.json
> Allow to deserialize error loxone message

- src/main/java/cz/smarteon/loxone/system/status/AirBaseExtension.java
- src/main/java/cz/smarteon/loxone/system/status/AirDevice.java
- src/main/java/cz/smarteon/loxone/system/status/BasicExtension.java
- src/main/java/cz/smarteon/loxone/system/status/DaliExtension.java
- src/main/java/cz/smarteon/loxone/system/status/Extension.java
- src/main/java/cz/smarteon/loxone/system/status/OneWireExtension.java
- src/main/java/cz/smarteon/loxone/system/status/TreeDevice.java
- src/main/java/cz/smarteon/loxone/system/status/TreeExtension.java
- src/main/java/cz/smarteon/loxone/system/status/TreeToAirBridge.java
- src/main/java/cz/smarteon/loxone/system/status/UnrecognizedExtension.java
- src/main/java/cz/smarteon/loxone/system/status/Updatable.java
- src/main/java/cz/smarteon/loxone/system/status/UpdatableDevice.java
- src/test/groovy/cz/smarteon/loxone/system/status/MiniserverStatusTest.groovy
- src/test/resources/system/status/status.xml
> Support update info in status

- src/main/java/cz/smarteon/loxone/Loxone.java
- src/main/java/cz/smarteon/loxone/LoxoneAuth.java
- src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
- src/test/groovy/cz/smarteon/loxone/LoxoneAuthTest.groovy
- src/test/groovy/cz/smarteon/loxone/LoxoneTest.groovy
- src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
> Make the visualization password optional

- src/main/java/cz/smarteon/loxone/system/status/AirDevice.java
- src/main/java/cz/smarteon/loxone/system/status/AirDeviceBase.java
- src/main/java/cz/smarteon/loxone/system/status/AirDeviceDeserializer.java
- src/main/java/cz/smarteon/loxone/system/status/MultiExtensionAir.java
- src/main/java/cz/smarteon/loxone/system/status/TreeDevice.java
- src/main/java/cz/smarteon/loxone/system/status/TreeDeviceBase.java
- src/main/java/cz/smarteon/loxone/system/status/TreeDeviceDeserializer.java
- src/main/java/cz/smarteon/loxone/system/status/TreeToAirBridge.java
- src/test/groovy/cz/smarteon/loxone/system/status/MiniserverStatusTest.groovy
- src/test/resources/system/status/status.xml
> Introduce multi extension air support

- build.gradle.kts
- src/test/groovy/cz/smarteon/loxone/MockWebSocketServer.groovy
* Version 1.3 dependent on junit4 stopped working in IDEA
* with spock 2.0 groovy 3.0 came - some syntax adjustments needed
> Upgrade spock to 2.0

- README.md
- src/main/java/cz/smarteon/loxone/LoxoneCrypto.java
> Use encryption algorithm returned with user key

- src/main/java/cz/smarteon/loxone/Loxone.java
- src/main/java/cz/smarteon/loxone/LoxoneAuth.java
- src/main/java/cz/smarteon/loxone/LoxoneHttp.java
- src/main/java/cz/smarteon/loxone/LoxoneProfile.java
- src/main/java/cz/smarteon/loxone/TokenRepository.java
- src/test/kotlin/LoxoneAuthTest.kt
- src/test/kotlin/LoxoneProfileTest.kt
- src/test/kotlin/LoxoneWebSocketIT.kt
new class wrapping endpoint and credentials
> Introduce LoxoneProfile and TokenRepository

- src/main/java/cz/smarteon/loxone/LoxoneEndpoint.java
- src/test/kotlin/LoxoneEndpointTest.kt
> Introduce support for cloud address

- build.gradle.kts
- src/main/java/cz/smarteon/loxone/Codec.java
- src/test/kotlin/mock/MockServer.kt
Updated versions for:
jackson - 2.13.0 -> 2.13.3
jadler - 1.3.0 -> 1.3.1
ktor - 2.0.0-beta-1 -> 2.0.3
Fixed kotlin compile to Java 11 version
> Dependency updates

- src/main/java/cz/smarteon/loxone/system/status/GenericNetworkDevice.java
- src/main/java/cz/smarteon/loxone/system/status/MiniserverStatus.java
- src/main/java/cz/smarteon/loxone/system/status/NetworkDevices.java
- src/test/kotlin/system/status/MiniserverStatusTest.kt
- src/test/resources/system/status/status.xml
> Introduce GenericNetworkDevice to system status

- src/main/java/cz/smarteon/loxone/LoxoneTime.java
- src/main/java/cz/smarteon/loxone/message/Token.java
- src/main/java/cz/smarteon/loxone/user/User.java
- src/test/kotlin/LoxoneTimeTest.kt
> Introduce LoxoneTime helper

- src/main/java/cz/smarteon/loxone/Loxone.java
- src/main/java/cz/smarteon/loxone/app/Control.java
- src/main/java/cz/smarteon/loxone/app/state/AnalogInfoControlState.java
- src/main/java/cz/smarteon/loxone/app/state/ControlState.java
- src/main/java/cz/smarteon/loxone/app/state/DigitalInfoControlState.java
- src/main/java/cz/smarteon/loxone/app/state/LockableControlState.java
- src/main/java/cz/smarteon/loxone/app/state/Locked.java
- src/main/java/cz/smarteon/loxone/app/state/LoxoneState.java
- src/main/java/cz/smarteon/loxone/app/state/SwitchControlState.java
- src/main/java/cz/smarteon/loxone/app/state/events/LockedEvent.java
- src/main/java/cz/smarteon/loxone/message/LoxoneEvent.java
- src/main/java/cz/smarteon/loxone/message/TextEvent.java
- src/main/java/cz/smarteon/loxone/message/ValueEvent.java
- src/test/kotlin/app/state/AnalogInfoControlStateTest.kt
- src/test/kotlin/app/state/DigitalInfoControlStateTest.kt
- src/test/kotlin/app/state/LoxoneStateTest.kt
- src/test/kotlin/app/state/SwitchControlStateTest.kt
- src/test/resources/app/LoxAppSwitch.json
New pull request with same changes + added tests.
The LoxoneState class needs some help for testing, i'm still a newbie with the used mocking framework and with kotlin code.
> First draft for state retention

- src/main/java/cz/smarteon/loxone/LoxoneTime.java
- src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
- src/main/java/cz/smarteon/loxone/LoxoneWebsocketClient.java
> Fix race condition when creating websocket
